import type { ComboPage } from "./types";
import { localSeoCombos } from "./local/local-seo-combos";

/**
 * Service × industry pages. Only pairings with real search demand and
 * something specific to say get an entry; everything else stays unbuilt.
 * Each entry is written for its pairing — see the quality gate in
 * src/seo/quality.ts and e2e/seo.spec.ts.
 */
export const comboPages: ComboPage[] = [
  {
    service: "seo",
    industry: "ecommerce",
    metaTitle: "Ecommerce SEO Agency for Category & Product Search",
    metaDescription:
      "Ecommerce SEO built around collection and product templates, faceted navigation and buying guides — so organic search brings in orders, not just visits.",
    primaryQuery: "ecommerce seo agency",
    updated: "2026-09-29",
    lead:
      "In online retail, SEO is mostly a templating problem. The pages that earn revenue are collections and products, generated by the thousand — and the decisions that make them rank are made once, in the template.",
    angle: [
      "Content-led SEO wins for publishers. Stores win differently: most commercial searches land on a category or collection page, so the work is making those pages the best answer for a query like 'linen duvet covers' — useful copy, the right products, filters that help rather than multiply URLs.",
      "The catalog changes constantly. Products sell out, seasons turn over, variants multiply. A store's SEO has to hold up while inventory moves, which means rules for out-of-stock pages, discontinued products and variants set in advance rather than handled one at a time.",
    ],
    priorities: [
      { title: "Collection pages that answer the search", detail: "Clear headings matched to how people search, a short useful introduction, internal links to sub-collections, and products ordered for the shopper rather than the warehouse." },
      { title: "Faceted navigation under control", detail: "Decide which filter combinations deserve their own indexable page (real search demand) and keep the rest out of the index, so crawl effort goes to pages that can rank." },
      { title: "Product templates with unique substance", detail: "Manufacturer descriptions are duplicated across every retailer. Original copy, specifications, sizing help and reviews give a product page a reason to rank." },
      { title: "Buying guides that feed collections", detail: "Guides answer research-stage questions and link to the collections that sell the answer — the bridge between informational and commercial search." },
    ],
    pitfalls: [
      { title: "Indexing every filter", detail: "Letting each color, size and price combination become an indexable URL creates thousands of near-duplicates and dilutes the pages that matter." },
      { title: "Deleting sold-out products", detail: "Removing a page that ranks throws away its authority. Keep it live with alternatives when the product returns, redirect to the closest match when it won't." },
      { title: "Blog posts disconnected from the catalog", detail: "Content that ranks but never links to a product or collection builds traffic without revenue." },
    ],
    measures: [
      "Organic revenue by template (collection, product, guide)",
      "Non-brand clicks to collection pages",
      "Indexed collection and product URLs vs. intended",
      "Organic conversion rate by landing template",
    ],
    faqs: [
      { q: "Does ecommerce SEO work on Shopify?", a: "Yes, with some platform constraints to work around — fixed URL prefixes, duplicate product URLs through collections, and limited control over some technical settings. None of them prevent strong results; they shape how the fixes are made." },
      { q: "Should product pages or category pages be the priority?", a: "Usually categories first. They target broader commercial searches with more volume, and a strong category page lifts the products linked from it." },
      { q: "How do you handle seasonal collections?", a: "Keep evergreen seasonal URLs (for example, a holiday gift collection) live year-round and update them each season, so the authority they earn carries into the next one." },
    ],
  },
  {
    service: "seo",
    industry: "b2b-saas",
    metaTitle: "SaaS SEO Agency Focused on Pipeline, Not Pageviews",
    metaDescription:
      "SEO for software companies: comparison, integration and use-case pages that meet buyers near a decision, with organic visits tied to trials and pipeline.",
    primaryQuery: "saas seo agency",
    updated: "2026-09-29",
    lead:
      "Software buyers search for their problem long before they search for a vendor. SaaS SEO means being there for both searches — and proving, in the CRM, which one turned into revenue.",
    angle: [
      "Most software categories have a narrow band of high-intent queries — '[category] software', '[competitor] alternatives', '[tool] integration' — surrounded by a much larger field of how-to and jobs-to-be-done searches. The narrow band converts but is hard to win. The wide field ranks more easily and only pays off when each article hands the reader to the product at the moment the problem feels expensive.",
      "The sales motion changes what counts as success. A product-led company can watch organic visitors sign up and activate in the same week. A sales-led company waits months between a first organic visit and a signed contract, so search landing pages have to be connected to opportunities in HubSpot or Salesforce — otherwise organic looks like a content budget with no return and gets cut at the next planning cycle.",
    ],
    priorities: [
      { title: "Decision-stage pages first", detail: "Comparison, alternatives, use-case and integration pages sit closest to a purchase. Write them fairly — a comparison that pretends the other product has no strengths persuades nobody who has used it." },
      { title: "Articles that double as demos", detail: "Tutorials built around the product actually doing the job, with real screenshots and steps, so a reader who arrived with a question leaves having seen the workflow." },
      { title: "Integration and template pages with real substance", detail: "If the product connects to dozens of tools or ships templates, each can earn a page — but only with setup detail, use cases and limits specific to that pairing, not a name swapped into a shell." },
      { title: "Docs and marketing site pulling together", detail: "Help documentation often already ranks for long-tail product queries. Shared navigation, deliberate subdomain decisions and internal links let that authority reach the commercial pages." },
    ],
    pitfalls: [
      { title: "Glossary sprawl", detail: "Broad definitional posts attract students and job seekers. Sessions climb, trials don't, and the program loses credibility with sales." },
      { title: "Marketing pages rendered in the browser", detail: "A marketing site shipped as a client-rendered single-page app can leave search engines with late or partial content. Server-rendered or statically generated pages remove the doubt." },
      { title: "Reporting traffic instead of opportunities", detail: "Without organic tied to trials, demos and pipeline in the CRM, even a working program can't defend its budget." },
    ],
    measures: [
      "Organic trials and demo requests by landing page",
      "Pipeline sourced or influenced by organic search",
      "Clicks from comparison, alternative and integration queries",
      "Activation rate of organically acquired sign-ups",
      "Non-brand clicks to product and use-case pages",
    ],
    faqs: [
      { q: "Should we publish pages comparing ourselves to competitors?", a: "Usually, yes — buyers search for those comparisons whether you publish them or not. The pages work when they're accurate about where each product fits, including cases where the other option is the better choice." },
      { q: "How long before SaaS SEO contributes to pipeline?", a: "Decision-stage pages on a domain with existing authority can start contributing within a quarter or two. A newer domain building from scratch takes longer, and we don't guarantee rankings on any timeline." },
      { q: "Should our docs live on a subdomain or a subfolder?", a: "Either can work. Subfolders make it simpler for authority to flow between docs and marketing pages, but the right call depends on how the docs are built and who maintains them — a rushed migration can cost more than it gains." },
    ],
  },
  {
    service: "seo",
    industry: "healthcare",
    metaTitle: "Healthcare SEO Agency for Practices & Health Systems",
    metaDescription:
      "Healthcare SEO for local practices and health systems: provider and location pages, clinician-reviewed content and tracking designed around HIPAA limits.",
    primaryQuery: "healthcare seo agency",
    updated: "2026-09-29",
    lead:
      "Patients search in two modes: trying to understand a symptom, and trying to find someone nearby who treats it. Healthcare SEO has to serve both, under a stricter standard of accuracy than almost any other field.",
    angle: [
      "Google's search quality guidelines group health with finance and safety as 'Your Money or Your Life' topics, where poor information can cause real harm, and they put heavy weight on demonstrated expertise. For a practice or health system, that translates into medical content written or reviewed by named clinicians, credentials visible on the page, a date of last clinical review, and no claim the organization couldn't stand behind in an exam room.",
      "Most of the searches that fill appointment books are local: 'pediatric dentist near me', 'orthopedic urgent care', a physician's name. Those are won with location and provider pages, a well-maintained Google Business Profile for each site, consistent directory listings and reviews. Measurement carries its own constraint — HIPAA limits what health information can flow to analytics and ad platforms, so tracking has to be designed with the privacy team before a single tag goes live.",
    ],
    priorities: [
      { title: "Location and provider pages", detail: "One substantial page per location and per clinician: services offered, insurance accepted, hours, accessibility, languages spoken and a clear route to booking, each matched to its listing in Google." },
      { title: "A visible clinical review process", detail: "Writers can draft; a qualified clinician reviews, is named with credentials, and re-reviews when guidance changes. The review date shows on the page." },
      { title: "Condition and treatment pages in patient language", detail: "What a procedure involves, who it suits, what recovery looks like and when to seek care — organized around how patients describe the problem, not how it's coded for billing." },
      { title: "Tracking built around protected health information", detail: "Audit every pixel and analytics tag on booking, condition and portal pages; remove or reconfigure anything that could send health data to a third party, and review the setup with your privacy officer." },
    ],
    pitfalls: [
      { title: "Ad pixels on sensitive pages", detail: "A standard marketing tag on an appointment form or condition page can transmit information regulators may treat as protected. That's a compliance exposure first and a measurement question second." },
      { title: "Stale listings after practice changes", detail: "Merged practices, moved offices and departed providers left live in directories send patients to the wrong door and muddle local rankings." },
      { title: "Unreviewed symptom articles", detail: "Generic health content with no named reviewer competes against large medical publishers, rarely wins, and weakens trust in the rest of the site." },
    ],
    measures: [
      "Appointment requests and calls from organic and local search, by location",
      "Business Profile calls, direction requests and website clicks",
      "Local visibility for priority service-line searches",
      "Share of medical pages with a current clinician review",
      "Organic entrances to provider pages",
    ],
    faqs: [
      { q: "Does HIPAA restrict SEO?", a: "The content and optimization work itself isn't the concern — tracking is. What analytics and advertising tags collect on pages about conditions, appointments or patient accounts needs review, and we work with your privacy and legal teams rather than making that call alone." },
      { q: "Do our physicians need to write the content?", a: "No. Experienced health writers can draft it, but a qualified clinician should review each medical page and be named as the reviewer. We keep the ask small: a focused review pass, not a writing assignment." },
      { q: "How should a multi-location practice handle Google Business Profiles?", a: "Each physical location gets its own verified profile with accurate hours, services and categories. Individual provider profiles can help too, provided they follow Google's guidelines for practitioners and are updated when people join or leave." },
      { q: "Can we reply to patient reviews?", a: "Yes, carefully. Confirming that a reviewer is a patient, or referring to their care, can itself disclose protected information, so replies should stay general and move specifics to a private channel." },
    ],
  },
  {
    service: "seo",
    industry: "professional-services",
    metaTitle: "Professional Services SEO for Law, Accounting & Advisory",
    metaDescription:
      "SEO for law firms, accountants and consultancies: practice-area pages, bios that rank for names, and expert content reviewed by the people who do the work.",
    primaryQuery: "professional services seo",
    updated: "2026-09-29",
    lead:
      "Clients hire a firm on trust, and they check expertise before they pick up the phone. SEO for professional services turns what the firm actually knows — its practice areas, its people, its point of view — into pages that pass that check.",
    angle: [
      "In a firm, the practitioners are the product. Searches often carry a person's name, a practice area plus a city, or a specific situation — 'selling a business with an earnout', 'sales tax nexus for remote sellers'. Bio pages, practice-area pages and situation-led articles do most of the ranking, yet many firms treat bios as a headshot and a paragraph and hide practice detail behind a contact form.",
      "Legal, tax and financial topics face the same scrutiny as health information, because wrong answers hurt people. Content needs a credentialed author, the jurisdiction stated plainly and professional conduct rules respected — bar advertising rules in some jurisdictions restrict terms like 'specialist' or how past results can be described, so the firm's ethics or compliance lead should review. Search volume is small and scattered, so a handful of qualified inquiries matters more than any traffic chart.",
    ],
    priorities: [
      { title: "Practice-area pages with depth", detail: "One page per service line, with sub-pages where demand justifies them, explaining the matters handled, how an engagement runs, who is involved and what a client should prepare." },
      { title: "Bios built to be found", detail: "Admissions, credentials, focus areas, publications and speaking, marked up with Person structured data and linked from every article that person writes or reviews." },
      { title: "Content that starts from the client's situation", detail: "Articles framed around circumstances clients actually face, drafted from short practitioner interviews and reviewed by the person who handles those matters." },
      { title: "A local footprint for each office", detail: "A location page and Google Business Profile per office, with name, address and phone kept identical across legal, accounting and professional directories." },
    ],
    pitfalls: [
      { title: "Articles no practitioner has read", detail: "Ghostwritten content that skips expert review risks inaccurate guidance and conduct-rule problems — and readers who know the field notice." },
      { title: "Ranking for clients you can't serve", detail: "A regional firm that wins broad national definitions draws readers from jurisdictions it isn't licensed in, inflating traffic without adding work." },
      { title: "Pages that say 'contact us' and little else", detail: "When a page gives no sense of process, fit or next steps, search engines and prospects both have too little to judge the firm on." },
    ],
    measures: [
      "Qualified inquiries from organic search, by practice area",
      "Organic entrances to bio and practice-area pages",
      "Local visibility for practice area plus city searches, per office",
      "Organic inquiries that became engagements, from the intake system or CRM",
    ],
    faqs: [
      { q: "Does SEO matter for a firm that grows through referrals?", a: "Yes. Referred prospects almost always look up the firm and the individual before they call, and a thin bio or missing practice page can undo a strong referral. SEO also opens a second source of work that doesn't depend on who knows whom." },
      { q: "Can we mention outcomes or past matters?", a: "It depends on the professional rules where you practice, and on client confidentiality. We write about the kinds of matters you handle without promising results, and your ethics or compliance lead approves anything that describes outcomes." },
      { q: "How much time does this take from our partners?", a: "Less than most expect. A short interview per topic and a review pass on the draft is usually enough — our writers do the drafting, structure and optimization." },
    ],
  },
  {
    service: "seo",
    industry: "home-services",
    metaTitle: "Local SEO for Home Services: Maps, Reviews & City Pages",
    metaDescription:
      "Local SEO for plumbers, HVAC, roofers and other home services: Business Profile work, service-area pages with real local proof, and reviews that win calls.",
    primaryQuery: "local seo for home services",
    updated: "2026-09-29",
    lead:
      "A burst pipe or a dead furnace produces a search with a location baked in. Home services SEO is decided in the map results and on service-area pages, and it pays off in booked jobs rather than ranking reports.",
    angle: [
      "For 'near me' and 'service plus town' searches, the map pack — a handful of businesses under a map — usually sits above the regular results. Placement there depends on the Google Business Profile: the right primary category, a full services list, an accurate service area, hours that match when the phones are answered, photos of real jobs, and a steady run of reviews that describe the work.",
      "Service-area businesses face a structural problem: they work across many towns but have one address, and map visibility weakens with distance from it. Reaching surrounding towns takes pages for each area with genuinely local substance — permit quirks, typical housing stock, the problems that come up there, jobs completed nearby. Call tracking adds another wrinkle, because tracking numbers placed carelessly on listings break the name, address and phone consistency local rankings rely on.",
    ],
    priorities: [
      { title: "A complete, active Business Profile", detail: "Correct categories, every service listed, service areas set, job photos added regularly, questions answered, and a review request built into the moment a job is marked complete." },
      { title: "Service and town pages with local proof", detail: "Pages for the highest-value services in priority towns, each carrying photos, details and reviews from jobs in that area rather than a copied template." },
      { title: "Consistent citations with call tracking done safely", detail: "Name, address and main phone number identical across directories and trade associations. If the Business Profile uses a tracking number, the main number stays listed as an additional phone, as Google's guidelines describe." },
      { title: "Seasonal and emergency pages ahead of demand", detail: "Furnace, AC, storm-damage and freeze-related pages published before the season turns, with same-day or after-hours availability stated only where it's true." },
    ],
    pitfalls: [
      { title: "Swapped-name city pages", detail: "Dozens of identical pages with the town name changed are what Google's spam policies call doorway pages. They rarely rank and can drag down the rest of the site." },
      { title: "Keywords stuffed into the business name", detail: "Adding 'Best Emergency Plumber' to the listing name breaks Business Profile guidelines and puts the profile at risk of suspension." },
      { title: "Treating reviews as a one-off push", detail: "A burst of reviews followed by silence looks odd and goes stale. Recency and steady volume do more than a single campaign." },
    ],
    measures: [
      "Booked jobs from organic and map results, by service and town",
      "Calls and direction requests from the Business Profile",
      "Map visibility across a grid of the service area",
      "Review volume, recency and average rating",
      "Calls and forms per organic landing page",
    ],
    faqs: [
      { q: "Can we rank in towns where we don't have an office?", a: "In the regular organic results, yes, with strong service-area pages. Map placement is harder the farther a town is from your address, which is why the organic pages carry more of the load for outlying areas." },
      { q: "How do we get more reviews without breaking the rules?", a: "Ask every customer at job completion, ideally by text with a direct link, and reply to every review. Don't offer discounts or gifts in exchange — Google's policies prohibit incentivized reviews." },
      { q: "How quickly does local SEO show results?", a: "Business Profile fixes can change map visibility within weeks. Service-area pages and review momentum build over a few quarters, and we don't guarantee positions in either." },
      { q: "Is this the same as Local Services Ads?", a: "No. Local Services Ads are a paid, pay-per-lead product where available; local SEO covers the map and organic results you don't pay per click for. Many home service businesses run both." },
    ],
  },
  {
    service: "paid-media",
    industry: "ecommerce",
    metaTitle: "Ecommerce PPC Agency for Shopping, PMax & Paid Social",
    metaDescription:
      "Ecommerce PPC run from the product feed out: Shopping and Performance Max structured by margin, catalog ads on Meta, and results judged on profit, not ROAS.",
    primaryQuery: "ecommerce ppc agency",
    updated: "2026-09-29",
    lead:
      "In online retail, the ads are built from the catalog. Titles, images, prices and stock status in the product feed shape what Shopping, Performance Max and Meta catalog campaigns can achieve before a bid is ever set.",
    angle: [
      "Google Shopping, Performance Max and Meta's Advantage+ catalog ads assemble ads from product data. A feed with vague titles, missing GTINs or stale availability caps reach however well the campaigns are structured, so much of the real work is in Merchant Center: titles rewritten around how people search, complete attributes, and custom labels that tag each product by margin band, bestseller status or season.",
      "Those labels matter because return on ad spend rewards the wrong behavior on its own. A campaign can hit its target by selling low-margin items to people who were already customers. We split brand from non-brand, separate new-customer acquisition from repeat buyers, and set targets on contribution margin — then compare what the platforms report against actual orders in the store's back end.",
    ],
    priorities: [
      { title: "A feed built for search", detail: "Product titles that lead with the terms shoppers use, correct categories and identifiers, accurate availability and sale prices, and supplemental feeds to fix what the store platform exports badly." },
      { title: "Campaigns segmented by margin and role", detail: "Hero products, long-tail catalog, clearance and new launches get separate budgets and targets, so the high-margin lines aren't starved by volume sellers." },
      { title: "Paid social creative beyond the catalog", detail: "Dynamic product ads handle retargeting well; reaching new customers usually needs demonstration video, creator content and offers tested on a regular cadence." },
      { title: "Conversion data that survives privacy limits", detail: "Server-side events through Meta's Conversions API and Google's enhanced conversions, checked against Shopify or the order system, with holdout tests where spend allows." },
    ],
    pitfalls: [
      { title: "Letting Performance Max spend on brand", detail: "Without brand exclusions and feed segmentation, it can drift toward branded searches and remarketing — easy conversions that inflate results without adding customers." },
      { title: "Scaling into sold-out stock", detail: "Pushing budget behind products that are about to run out wastes the learning period and the spend. Stock levels need to feed campaign rules." },
      { title: "Judging every campaign on one ROAS target", detail: "A single number across prospecting, retargeting and brand hides which campaigns win new customers and which recycle existing ones." },
    ],
    measures: [
      "Contribution margin after ad spend",
      "New-customer acquisition cost",
      "Non-brand return, split from brand and retargeting",
      "Merchant Center disapprovals and missing attributes",
      "Marketing efficiency ratio: total revenue over total ad spend",
    ],
    faqs: [
      { q: "Should we run Performance Max or standard Shopping campaigns?", a: "Often both. Standard Shopping gives more control and clearer search-term data for priority products, while Performance Max reaches across Google's inventory. The feed and segmentation decide how well either performs." },
      { q: "What ROAS target should we use?", a: "One derived from your own margins and customer value, not an industry rule of thumb. We work back from contribution margin and repeat-purchase behavior to set break-even and growth targets by product group." },
      { q: "Do you manage Meta and TikTok alongside Google?", a: "Yes. Search and Shopping capture existing demand; paid social creates it. Running them together lets creative and product learnings move between channels instead of sitting in separate reports." },
      { q: "How do you deal with attribution gaps from privacy changes?", a: "By sending server-side conversion data to the platforms, reconciling reported conversions with real orders, and using blended measures and holdout tests rather than trusting any single platform's view." },
    ],
  },
  {
    service: "paid-media",
    industry: "b2b-saas",
    metaTitle: "B2B SaaS Paid Media Agency: LinkedIn, Search & Pipeline",
    metaDescription:
      "Paid media for B2B SaaS optimized to qualified pipeline: CRM-connected conversions, high-intent search, and LinkedIn programs aimed at your target accounts.",
    primaryQuery: "b2b saas paid media agency",
    updated: "2026-09-29",
    lead:
      "A software buyer might click an ad this month and sign a contract two quarters later, after a buying committee has had its say. Paid media for SaaS works only when the platforms learn from that eventual deal rather than the first form fill.",
    angle: [
      "Ad platforms optimize toward whatever conversion they're fed. Feed them raw form submissions and they get very good at finding people who fill in forms — students, competitors, vendors, job seekers. Importing qualified-pipeline stages from HubSpot or Salesforce back into Google Ads, LinkedIn and Meta as offline conversions redirects the bidding toward the kind of accounts that actually buy.",
      "Each channel plays a different part. LinkedIn is expensive per click but targets by job title, company and uploaded account lists, which suits account-based programs and building awareness in a defined market. Search captures demand that already exists, including category and competitor terms. Meta and YouTube can reach broad user bases cheaply for product-led tools. Planning the mix means deciding which channels create demand and which capture it — and not grading the first kind on last-click results.",
    ],
    priorities: [
      { title: "CRM stages sent back to the platforms", detail: "Qualified lead, opportunity and closed-won events imported from the CRM, with the click identifiers captured at form submit so matches actually happen." },
      { title: "Full coverage of high-intent search", detail: "Category, competitor, alternative and integration queries, each sent to a landing page written for that search rather than the homepage." },
      { title: "Account-based programs on LinkedIn", detail: "Target account lists agreed with sales, message sequences by role, and reporting on engagement within those accounts, not just clicks." },
      { title: "Offers matched to buying stage", detail: "Demo or trial for high intent; interactive product tours, templates or tools for evaluators; ungated, useful content for audiences that don't know you yet." },
    ],
    pitfalls: [
      { title: "Asking cold audiences for a demo", detail: "Serving a 'book a demo' ad to people who've never heard of the product burns budget and teaches the algorithm little." },
      { title: "Optimizing for lead volume", detail: "Cheap leads that sales rejects make paid look productive in the dashboard and useless in the pipeline review." },
      { title: "Last-click verdicts on awareness spend", detail: "LinkedIn prospecting rarely gets the final click. Self-reported attribution on forms and pipeline influence by account give a fairer read." },
    ],
    measures: [
      "Pipeline created from paid, by channel and campaign",
      "Cost per sales-qualified opportunity",
      "Win rate and deal size of paid-sourced opportunities",
      "Engagement from target accounts on LinkedIn",
      "Paid channels named in self-reported attribution",
    ],
    faqs: [
      { q: "Is LinkedIn advertising worth the cost?", a: "For companies with a defined buyer and a meaningful contract value, often yes — no other platform targets by title and company as precisely. For low-price, self-serve tools, cheaper channels usually do more." },
      { q: "Should we bid on competitor names?", a: "It can work, and bidding on a competitor's name as a keyword is generally allowed, though using the trademark in ad text can be restricted if the owner objects. The landing page needs to be a fair comparison, or the clicks won't convert." },
      { q: "How soon can we judge whether paid is working?", a: "Leading signals such as qualified meetings show within weeks. Pipeline takes a quarter or so to read, and closed revenue follows your normal sales cycle, so we agree the checkpoints up front." },
    ],
  },
  {
    service: "paid-media",
    industry: "home-services",
    metaTitle: "Google Ads for Home Services: LSA, Search & Call Tracking",
    metaDescription:
      "Google Ads for plumbing, HVAC, roofing and other home services: Local Services Ads, tight geo-targeting, and optimization to booked jobs instead of raw calls.",
    primaryQuery: "google ads for home services",
    updated: "2026-09-29",
    lead:
      "When a water heater fails, the homeowner calls one of the first businesses they see. Paid search for home services is a contest of speed, trust signals and whether someone answers the phone.",
    angle: [
      "Home services has more ad formats to choose from than most categories. Local Services Ads — the badged units at the very top of the page in markets where Google offers them — charge per lead and typically require background, license and insurance checks before they run. Standard search ads charge per click and give full control over keywords, schedules and landing pages. Performance Max and Maps placements fill in around them. The right mix depends on the trade, the town and the office's capacity to take calls.",
      "Much of the waste happens after the click. Missed calls, slow callbacks and voicemail at peak times hand paid leads to competitors, and in the ad account that shows up as a campaign problem. We review call logs and recordings alongside the campaigns, set schedules around when the phones are staffed, and draw service radiuses around the towns where jobs are profitable to reach.",
    ],
    priorities: [
      { title: "Call tracking tied to booked jobs", detail: "Tracking numbers on the site, call recording, and booked-job outcomes from the field service software — ServiceTitan, Jobber, Housecall Pro — imported back into Google Ads." },
      { title: "Separate campaigns for repair and replacement", detail: "An emergency repair and a full system install differ in value, urgency and search terms, so they get their own budgets, bids and landing pages." },
      { title: "Local Services Ads managed, not left running", detail: "Accurate service categories and hours, fast responses to leads, reviews kept current, and invalid leads disputed promptly." },
      { title: "Landing pages built for the phone", detail: "One page per high-value job type, with the number visible on mobile, license and insurance details, recent reviews and financing where offered." },
    ],
    pitfalls: [
      { title: "Broad match with no negatives", detail: "Without exclusions for 'jobs', 'salary', 'DIY', 'parts' and 'how to', budgets drain into searches from people who will never book a visit." },
      { title: "Counting every call as a conversion", detail: "Existing customers, vendors and spam calls all register as conversions unless calls are filtered by length and outcome." },
      { title: "Running ads while no one can answer", detail: "After-hours or weekend spend without an answering service or on-call tech pays for leads that go straight to voicemail." },
    ],
    measures: [
      "Cost per booked job, by service type",
      "Answer rate on paid calls",
      "Lead-to-booked-job conversion rate",
      "Revenue per paid-sourced job, from field service records",
      "Share of Local Services Ads leads disputed and credited",
    ],
    faqs: [
      { q: "Should we use Local Services Ads or regular Google Ads?", a: "Usually both where Local Services Ads are available. They sit at the top of the page and bill per lead, while search ads give control over which jobs and towns you pay for. We set budgets across them based on cost per booked job, not per lead." },
      { q: "Should our ads run around the clock?", a: "Only when someone can take the call. Emergency trades with on-call staff can do well after hours; everyone else is better off concentrating spend when the office is open." },
      { q: "How do you handle seasonal swings?", a: "Budgets and messaging shift ahead of each season — cooling in early summer, heating before the first cold snap — and pull back in slow periods so the account isn't paying peak prices for off-season demand." },
      { q: "Can you connect ads to our field service software?", a: "In most cases, yes. Linking booked jobs and invoice values back to campaigns is what lets the account optimize for revenue instead of phone calls." },
    ],
  },
  {
    service: "paid-media",
    industry: "fintech",
    metaTitle: "Fintech Paid Advertising Within Financial Ad Policies",
    metaDescription:
      "Paid media for fintech built around financial ad policies and compliance review, optimized to funded and active accounts rather than installs or sign-ups.",
    primaryQuery: "fintech paid advertising",
    updated: "2026-09-29",
    lead:
      "Financial products are among the most tightly restricted things to advertise. Paid media for fintech starts by mapping what each platform and market allows, then builds growth inside those lines.",
    angle: [
      "Google and Meta both run dedicated policies for financial services, and the details differ by product type and country. Depending on where you advertise, you may need platform verification or certification before ads serve, specific disclosures on landing pages, or accept limits on targeting — Meta, for example, places credit and other financial product ads in a special ad category that restricts demographic and location targeting in many markets. Lending, investing, crypto, insurance and payments each carry their own rules, and those rules change, so every market plan is checked against current policy before creative is made.",
      "Claims need the same care. Rates, fees, rewards, approval language and statements about how deposits are protected all fall under financial promotion and consumer protection rules, which generally expect messaging to be clear, fair and balanced with risks. Your compliance team should approve every claim. We make that practical: a library of approved claims and disclosures, and review built into the testing calendar so experiments move without skipping sign-off.",
    ],
    priorities: [
      { title: "A policy and certification map by market", detail: "For each platform and country: what verification is required, which products are restricted or prohibited, what disclosures apply, and which targeting options are off the table." },
      { title: "An approved claims library", detail: "Pre-cleared headlines, benefit statements and disclaimers that creative teams can combine freely, so new variants need lighter review." },
      { title: "Optimization to funded or active accounts", detail: "Platforms fed events for identity verification passed, first deposit or first transaction — sent as minimal signals, never balances or credit details." },
      { title: "Creative that explains before it sells", detail: "What the product does, how it makes money, how it's regulated and how customer funds are handled, stated accurately and plainly." },
    ],
    pitfalls: [
      { title: "Launching before compliance review", detail: "Unreviewed claims lead to disapprovals, suspended ad accounts and, worse, regulatory exposure that no growth target justifies." },
      { title: "Optimizing to sign-ups", detail: "Many fintech sign-ups never finish identity checks or fund an account. Bidding on the top of that funnel buys volume that goes nowhere — and can attract fraud." },
      { title: "Oversharing with ad platforms", detail: "Passing account values, credit data or detailed financial attributes through pixels or conversion APIs creates privacy risk. Send the smallest signal that lets bidding work." },
    ],
    measures: [
      "Cost per funded or active account",
      "Identity verification completion rate of paid cohorts",
      "Early deposit or transaction activity of paid cohorts",
      "Ad disapproval and policy-issue rate",
      "Time from creative draft to compliance approval",
    ],
    faqs: [
      { q: "Do we need certification to advertise financial products?", a: "It depends on the product, the platform and the country — requirements differ across regions and change over time. We map current requirements for your markets, but confirming your regulatory obligations belongs with your legal and compliance team." },
      { q: "Can you write compliant ad copy?", a: "We write within the platform rules and your approved claims, and route everything through your compliance reviewers. We don't replace legal review; we make it faster to do properly." },
      { q: "Which channels suit fintech acquisition?", a: "Search captures high-intent product queries, app campaigns drive installs for mobile-first products, and paid social works within its financial ad restrictions. B2B fintech often adds LinkedIn. The mix depends on the product and the markets you're licensed in." },
      { q: "How do you measure app-based products?", a: "Through a mobile measurement partner connected to your product events, with platform reporting read alongside cohort data, since privacy frameworks on mobile limit user-level attribution." },
    ],
  },
  {
    service: "web-design",
    industry: "b2b-saas",
    metaTitle: "SaaS Website Design Agency for Clear, Fast Product Sites",
    metaDescription:
      "SaaS website design that makes an intangible product easy to evaluate — clear positioning, real product visuals, honest pricing and a CMS marketing can run.",
    primaryQuery: "saas website design agency",
    updated: "2026-09-29",
    lead:
      "A SaaS website has to explain a product nobody can hold to buyers who each want something different from it. The design job is making the product legible — and letting marketing publish without waiting on engineering.",
    angle: [
      "Software is abstract, so the site ends up carrying the first demo. Visitors try to work out what the product does, who it's for and whether it fits their stack within a few screens. Real interface views — simplified where that helps, never faked — interactive tours, integration listings and a straightforward pricing page do more than abstract illustration. And roles arrive with different questions: the champion wants use cases, the technical evaluator wants security, API and docs, the budget holder wants pricing and a clear path to talk to someone.",
      "SaaS positioning shifts often — a new segment, a new tier, a second product. A site built from bespoke pages hard-coded by the app team turns each shift into an engineering ticket. We design a component system inside the CMS so marketing can assemble feature, comparison and campaign pages on its own, and build it on a framework that renders on the server, passes Core Web Vitals and gives search engines clean markup.",
    ],
    priorities: [
      { title: "Messaging architecture before layouts", detail: "Category, audiences, use cases and differentiators agreed first, so navigation follows how buyers evaluate — by role, use case or industry — instead of the org chart." },
      { title: "Product visuals that stay current", detail: "Interface shown through simplified, component-based illustrations or a managed screenshot set, so the site doesn't show last year's product after every release." },
      { title: "A pricing page that answers questions", detail: "Tiers, limits and what's included laid out plainly, with an obvious route for teams that need a custom plan or procurement review." },
      { title: "Templates marketing can run", detail: "A component library and page templates for features, integrations, comparisons, customer stories and campaigns, in a CMS your team is comfortable editing." },
    ],
    pitfalls: [
      { title: "Writing in internal vocabulary", detail: "Product names and feature labels that make sense inside the company mean nothing to a first-time visitor comparing options." },
      { title: "Coupling the site to the app codebase", detail: "When the marketing site ships through the product release process, a headline change waits for a sprint. Separate stacks let each move at its own pace." },
      { title: "Launch-day design with no system behind it", detail: "A striking homepage and no reusable components means every new page after launch is either off-brand or waiting on a designer." },
    ],
    measures: [
      "Visitor-to-trial or demo conversion by page type",
      "Time to publish a new landing page",
      "Core Web Vitals at the 75th percentile: LCP ≤2.5s, INP ≤200ms, CLS ≤0.1",
      "Progression from pricing page to sign-up or sales contact",
      "Organic entrances to feature and integration pages",
    ],
    faqs: [
      { q: "Should our marketing site be separate from the product?", a: "Usually, yes. A separate marketing site, often on its own framework and CMS, lets marketing ship changes daily without touching the application. Shared design tokens keep the two visually consistent." },
      { q: "Which CMS do you recommend?", a: "It depends on who edits the site and how much custom functionality it needs. Headless options such as Sanity and Contentful suit teams with developers on hand; visual builders like Webflow suit teams that want to edit layouts directly. We choose after looking at your team and roadmap." },
      { q: "How long does a SaaS website redesign take?", a: "Most run roughly ten to sixteen weeks from kickoff to launch, depending on page count, how ready the messaging and content are, and the integrations involved." },
      { q: "Do you design the product interface as well?", a: "Yes, as separate product design work. Keeping the two in one team helps the marketing site show the product accurately and keeps the visual language consistent." },
    ],
  },
  {
    service: "cro",
    industry: "ecommerce",
    metaTitle: "Ecommerce Conversion Rate Optimization for Online Stores",
    metaDescription:
      "Ecommerce CRO grounded in funnel data: find where shoppers drop from product page to checkout, fix it, and test on revenue per visitor rather than clicks.",
    primaryQuery: "ecommerce conversion rate optimization",
    updated: "2026-09-29",
    lead:
      "A store rarely loses sales in one place. Shoppers slip away on the product page, in the cart, at a delivery charge revealed too late and in a checkout that asks for too much — and each leak needs evidence before it gets a fix.",
    angle: [
      "Stores generate an unusual amount of behavioral data: product views, add-to-carts, each checkout step, every payment attempt. That makes it possible to pin down where shoppers drop, split by device and traffic source, before deciding what to change. And because the value sits in a few templates — product, collection, cart, checkout — one validated improvement applies across the entire catalog at once.",
      "Two constraints shape the program. Traffic: many stores don't have enough orders to detect small changes with statistical confidence in a reasonable window, so tests need to be bolder, run on high-traffic templates, or target an earlier step like add-to-cart. Platform: hosted checkouts limit what can be edited — on Shopify, checkout changes go through its extensibility tools rather than free-form code — which moves effort to the pages before it. And conversion rate is never the goal by itself; a discount pop-up can raise it while quietly eroding margin.",
    ],
    priorities: [
      { title: "Funnel diagnosis by device and source", detail: "Step-by-step drop-off from analytics, session recordings and short on-site surveys, starting with mobile, where drop-off often looks different from desktop's." },
      { title: "Product pages that answer the last questions", detail: "Images that show scale and detail, sizing or fit help, and delivery date, shipping cost and returns stated right beside the add-to-cart button." },
      { title: "A shorter path through checkout", detail: "Express wallets such as Shop Pay, Apple Pay and PayPal offered early, guest checkout available, and no surprise costs at the final step." },
      { title: "Tests judged on revenue, not clicks", detail: "Hypotheses written before launch, sample sizes estimated from real traffic, and results read on revenue per visitor and margin." },
    ],
    pitfalls: [
      { title: "Stopping tests at the first good day", detail: "Checking results daily and calling a winner early produces effects that vanish after launch. Run full weekly cycles and stick to the planned sample." },
      { title: "Buying conversion rate with discounts", detail: "Pop-up codes and sitewide sales lift the rate and cut profit per order. The test metric has to include margin." },
      { title: "Copying another store's layout", detail: "What works for a different catalog, price point and audience is a hypothesis to test, not a fix to ship." },
    ],
    measures: [
      "Revenue per visitor",
      "Checkout completion rate by device",
      "Add-to-cart rate by product template",
      "Average order value and margin per order",
      "Tests completed per quarter with a conclusive result",
    ],
    faqs: [
      { q: "How much traffic do we need to run A/B tests?", a: "There's no universal threshold — it depends on your baseline conversion rate and the size of change you want to detect. We calculate it before testing, and for lower-traffic stores lean on research-led changes and tests on higher-funnel steps." },
      { q: "Will testing tools slow down our store?", a: "Client-side testing scripts can delay rendering and cause flicker. We keep them light, load them carefully and use server-side or theme-level testing where the platform allows." },
      { q: "Can you optimize the Shopify checkout?", a: "Within what Shopify permits — checkout extensions, payment options, shipping presentation and upsells. Most of the gains usually come from the product page and cart, where you have full control." },
      { q: "How long does each test run?", a: "At least one full week, and usually two or more, so weekday and weekend behavior are both captured. The planned sample size decides the end date, not the first promising result." },
    ],
  },
  {
    service: "email-marketing",
    industry: "ecommerce",
    metaTitle: "Ecommerce Email Marketing Agency for Flows & Retention",
    metaDescription:
      "Ecommerce email and SMS built on behavioral flows, clean store data and sound deliverability, so repeat orders come from the list rather than more discounts.",
    primaryQuery: "ecommerce email marketing agency",
    updated: "2026-09-29",
    lead:
      "Email is the channel a store owns outright, with no auction deciding who sees the message. Most of its revenue comes from automated flows triggered by what shoppers do — sent to a list kept healthy enough to reach the inbox.",
    angle: [
      "Flows do the steady work: welcome series, browse and cart abandonment, post-purchase, replenishment for products that run out, and win-back for customers who have gone quiet. They depend on product, order and customer data synced from Shopify or another platform into a tool like Klaviyo, so the quality of that sync decides how specific each message can be — the right product, the right timing, the right next recommendation.",
      "Reaching the inbox is now a requirement, not a nice-to-have. Gmail and Yahoo expect bulk senders to authenticate their domains with SPF, DKIM and DMARC, offer one-click unsubscribe and keep spam complaints low. Blasting discount campaigns to the entire list every few days pushes complaints up and teaches customers to wait for a code. Segmenting by engagement and purchase behavior protects sender reputation and margin at the same time.",
    ],
    priorities: [
      { title: "Core flows, branched by behavior", detail: "Welcome split between buyers and browsers, abandonment branched by cart value and category, post-purchase that teaches product use, and replenishment timed to how long the product lasts." },
      { title: "Store data synced and segmented", detail: "Engaged versus unengaged, first-time versus repeat, category affinity and expected next order, built from clean catalog and order events." },
      { title: "Deliverability foundations", detail: "Authenticated sending domain, a sunset policy for inactive profiles, and list growth only from sources with clear consent." },
      { title: "A campaign calendar with more than sales", detail: "Launches, restocks, guides and stories alongside planned promotions, so customers open for reasons other than a discount." },
    ],
    pitfalls: [
      { title: "Discounting everything", detail: "When every send carries a code, full-price purchases shrink and the list learns to wait. Promotions need a deliberate frequency." },
      { title: "Mailing profiles that never open", detail: "Sending to long-inactive subscribers drags down inbox placement for everyone, including the customers who do engage." },
      { title: "Trusting attributed revenue alone", detail: "Platform attribution credits email for orders that would have happened anyway. Holdout groups on key flows show what email actually adds." },
    ],
    measures: [
      "Revenue per recipient, by flow and campaign",
      "Repeat purchase rate of subscribed versus unsubscribed customers",
      "Spam complaint and unsubscribe rates",
      "Incremental revenue measured with holdout groups",
      "List growth from consented sources",
    ],
    faqs: [
      { q: "Do you work in Klaviyo?", a: "Yes — it's a common choice for Shopify stores — and we work in other email and SMS tools too. The flows and segmentation logic carry over; the build differs by platform." },
      { q: "How often should we email our list?", a: "As often as engagement holds up. Engaged segments can take more frequent sends than lapsed ones, so we set frequency by segment and watch complaints and unsubscribes rather than following a fixed rule." },
      { q: "Should we add SMS?", a: "Often, for time-sensitive messages like shipping updates, restocks and launches. SMS has stricter consent requirements than email in many markets, so opt-in collection and message content should be reviewed with your legal team before launch." },
      { q: "Do you design the emails too?", a: "Yes. We build modular templates that match the brand, render properly in dark mode and on mobile, and let your team assemble campaigns without starting from scratch each time." },
    ],
  },
  ...localSeoCombos,
];
